# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI/CD Pipeline

on:
  push:
  pull_request:
    branches:
      - main
      - back-end_drop
      - front-end_drop

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: JSDoc Action
      # You may pin to the exact commit or the version.
      # uses: andstor/jsdoc-action@2fb2b536605bdebace2b92abb0601155d5ddc688
      uses: andstor/jsdoc-action@v1.2.0
      with:
        # Source directory to build documentation from
        source_dir: ./codebase
        # Output folder for the generated documentation
        output_dir: ./codebaseDocs
        # Recurse into subdirectories when scanning for source files
        recurse: true
        # The path to a Markdown file to be used as a the front page
        front_page: ./codebase/CI-CD-pipeline.md
    - name: Install modules
      run: yarn
    - name: Run tests
      run: yarn test
  
  
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci # or yarn install
      - uses: sibiraj-s/action-eslint@v1
        with:
          eslintArgs: '--ignore-path=.gitignore --quiet'
          extensions: 'js,jsx,ts,tsx'
          annotations: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
